services:
  - type: web
    name: resume-scanner
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.main:app"
    envVars:
      - key: GEMINI_API_KEY
        sync: false